"
A GtkSourceBuffer object is the model for GtkSourceView widgets. It extends the GtkTextBuffer class by adding features useful to display and edit source code such as syntax highlighting and bracket matching. It also implements support for the undo/redo.

https://developer.gnome.org/gtksourceview/stable/GtkSourceBuffer.html
"
Class {
	#name : #GtkSourceBuffer,
	#superclass : #GtkTextBuffer,
	#category : #'Mars-Gtk-SourceView'
}
